USE db3;

CREATE TABLE books(
	TITLE  VARCHAR(200) NOT NULL,
	AUTHOR VARCHAR(200) NOT NULL,
	PRICE  DECIMAL      NOT NULL CHECK(PRICE>=0),
	RATING DECIMAL      CHECK(RATING>=1 AND RATING<=5),
	COVER  VARCHAR(512) DEFAULT('/unknown.png')
);